version: '3.7'

volumes:
  ranger_db_data: {}
  es_data: {}
  hadoop_namenode: {}
  hadoop_datanode: {}
  hive_db_data: {}

networks:
  default:
    external:
      name: ranger-env

services:

  # ------------
  # Serviços para o Ranger
  # ------------

  db:
    image: mysql:5.7
    volumes:
      - ranger_db_data:/var/lib/mysql
    restart: always
    container_name: ranger-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ranger
      MYSQL_USER: ranger
      MYSQL_PASSWORD: ranger
    expose:
      - "3306"
  
  ranger-admin:
    image: kadensungbincho/ranger-admin:2.1.0
    container_name: ranger-admin
    hostname: ranger
    depends_on:
      - db
    volumes:
      - ./ranger/admin/bootstrap.sh:/opt/ranger_admin/bootstrap.sh
      - ./ranger/admin/install.properties:/opt/ranger_admin/install.properties
    command: ["./bootstrap.sh"]
    ports:
      - "6080:6080"
    restart: always

  ranger-usersync:
    image: kadensungbincho/ranger-usersync:2.1.0
    container_name: ranger-usersync
    hostname: usersync
    depends_on:
      - ranger-admin
    volumes:
      - ./ranger/usersync/bootstrap.sh:/opt/ranger_usersync/bootstrap.sh
      - ./ranger/usersync/install.properties:/opt/ranger_usersync/install.properties
    command: ["./bootstrap.sh"]
    restart: always

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: ranger-es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=elasticsearch"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

    # ------------
    # Serviços para o HDFS
    # ------------
  namenode:
    image: kadensungbincho/ranger-hadoop-namenode:2.0.0-hadoop3.2.1-java8-ranger2.1.0
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hdfs/install.properties:/opt/ranger-hdfs-plugin/install.properties
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - hadoop.env

  # ------------
  # Serviços para o Yarn
  # ------------
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - hadoop.env

  # ------------
  # Serviços para o Hive
  # ------------
  hive-server:
    image: kadensungbincho/ranger-hive:2.0.0-hadoop3.2.1-java8-ranger2.1.0
    container_name: hive-server
    hostname: hive-server
    volumes:
      - ./hive/install.properties:/opt/ranger-hive-plugin/install.properties
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: kadensungbincho/ranger-hive:2.0.0-hadoop3.2.1-java8-ranger2.1.0
    container_name: hive-metastore
    hostname: hive-metastore
    env_file:
      - ./hadoop.env
    command: ["/run.sh", "metastore"]
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864 hive-db:3306"
    ports:
      - "9083:9083"

  hive-db:
    image: mysql:8.0.21
    container_name: hive-db
    hostname: hive-db
    volumes:
      - hive_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
  
  zoo:
    image: zookeeper:3.4.14
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
